; SPC700 MIDI driver (spcasm syntax).
;
; Polls the APU I/O ports for commands from the FPGA (see
; src/midi/midi_mailbox.v), acknowledges them by echoing the sequence
; number on port 3, and plays notes on the eight S-DSP voices.
;
;   port 0 ($F4)  opcode  {command, midi channel}   (channel ignored: omni)
;   port 1 ($F5)  arg0
;   port 2 ($F6)  arg1
;   port 3 ($F7)  sequence; a new value commits the command
;
; Commands: 1 NOTE_ON note vel, 2 NOTE_OFF note, 3 PROGRAM prog,
;           4 VOLUME value, 5 PAN value, 6 ALL_OFF.
;
; The instrument bank (sample directory, pitch table, instrument table,
; BRR data) is generated by tools/build_midi_image.py and included at the
; end; it defines sample_dir, pitch_table, instruments and NUM_INSTR.

; ---------------------------------------------------------------------------
; Hardware
; ---------------------------------------------------------------------------
CONTROL  = $F1
DSP_ADDR = $F2
DSP_DATA = $F3
PORT0    = $F4
PORT1    = $F5
PORT2    = $F6
PORT3    = $F7

; Per-voice DSP registers (add voice * $10)
V_VOL_L  = $00
V_VOL_R  = $01
V_PITCHL = $02
V_PITCHH = $03
V_SRCN   = $04
V_ADSR1  = $05
V_ADSR2  = $06
V_GAIN   = $07

; Global DSP registers
MVOL_L   = $0C
MVOL_R   = $1C
EVOL_L   = $2C
EVOL_R   = $3C
KON      = $4C
KOF      = $5C
FLG      = $6C
EFB      = $0D
PMON     = $2D
NON      = $3D
EON      = $4D
DIR      = $5D
ESA      = $6D
EDL      = $7D

MASTER_VOLUME = $50
; KON is latched, not accumulated, by the S-DSP: a second write within ~2
; samples replaces the first. A NOTE_ON already takes ~10 samples, so this
; wait (DBNZ loops of ~6 cycles; 32 SPC700 cycles per sample) is a safety
; margin for faster code paths such as batched key-ons.
KON_DELAY = 32

; ---------------------------------------------------------------------------
; Direct page variables
; ---------------------------------------------------------------------------
last_seq   = $00
cmd        = $01
arg0       = $02
arg1       = $03
tmp0       = $04
vbase      = $05   ; current voice * $10
cur_voice  = $06
best_v     = $07
best_age   = $08
age_ctr    = $09   ; incremented on every note-on
kof_shadow = $0A   ; KOF is a level register; keep the bits we want held
chan_prog  = $0B
chan_vol   = $0C
chan_pan   = $0D
amp        = $0E
v_on       = $10   ; [8] 1 while the key is held
v_note     = $18   ; [8]
v_age      = $20   ; [8] age_ctr at key-on
v_vel      = $28   ; [8]
DP_END     = $30

macro dsp_write(reg, value)
    mov DSP_ADDR, #<reg>
    mov DSP_DATA, #<value>
endmacro

; ---------------------------------------------------------------------------
; Entry point (the SPC image's PC points here)
; ---------------------------------------------------------------------------
org $0500
startpos
reset:
    mov x, #$FF
    mov sp, x

    mov a, #0
    mov x, #DP_END - 1
.clear:
    mov (x), a
    dec x
    bpl .clear

    mov chan_vol, #100
    mov chan_pan, #64

    mov CONTROL, #$00           ; timers off, IPL ROM unmapped
    %dsp_write(FLG, $20)        ; leave soft reset/mute, echo writes off
    %dsp_write(KON, $00)
    %dsp_write(KOF, $00)
    %dsp_write(DIR, sample_dir >> 8)
    %dsp_write(MVOL_L, MASTER_VOLUME)
    %dsp_write(MVOL_R, MASTER_VOLUME)
    %dsp_write(EVOL_L, $00)
    %dsp_write(EVOL_R, $00)
    %dsp_write(EFB, $00)
    %dsp_write(EON, $00)
    %dsp_write(NON, $00)
    %dsp_write(PMON, $00)
    %dsp_write(ESA, $FF)
    %dsp_write(EDL, $00)

; ---------------------------------------------------------------------------
; Mailbox loop
; ---------------------------------------------------------------------------
main:
    mov a, PORT3
    cbne last_seq, got_cmd
    bra main

got_cmd:
    mov tmp0, a
    mov cmd, PORT0
    mov arg0, PORT1
    mov arg1, PORT2
    mov a, PORT3
    cbne tmp0, got_cmd          ; sequence moved during the copy: re-read
    mov PORT3, a                ; acknowledge
    mov last_seq, a

    mov a, cmd
    xcn a
    and a, #$0F
    cmp a, #1
    bne .not_on
    call note_on
    bra main
.not_on:
    cmp a, #2
    bne .not_off
    call note_off
    bra main
.not_off:
    cmp a, #3
    bne .not_prog
    mov a, arg0
    and a, #NUM_INSTR - 1
    mov chan_prog, a
    bra main
.not_prog:
    cmp a, #4
    bne .not_vol
    mov chan_vol, arg0
    call refresh_volumes
    bra main
.not_vol:
    cmp a, #5
    bne .not_pan
    mov chan_pan, arg0
    call refresh_volumes
    bra main
.not_pan:
    cmp a, #6
    bne main
    call all_off
    bra main

; ---------------------------------------------------------------------------
; NOTE_ON: arg0 = note, arg1 = velocity
; ---------------------------------------------------------------------------
note_on:
    mov a, arg1
    bne .has_velocity
    jmp note_off
.has_velocity:
    call alloc_voice
    mov cur_voice, x
    inc age_ctr
    mov a, age_ctr
    mov v_age+x, a
    mov a, arg0
    mov v_note+x, a
    mov a, arg1
    mov v_vel+x, a
    mov a, #1
    mov v_on+x, a

    ; Stop holding this voice in key-off before keying it on again.
    mov a, voice_bit+x
    eor a, #$FF
    and a, kof_shadow
    mov kof_shadow, a
    mov DSP_ADDR, #KOF
    mov DSP_DATA, a

    mov a, x
    xcn a
    mov vbase, a

    ; Instrument: SRCN, ADSR1, ADSR2
    mov a, chan_prog
    asl a
    asl a
    mov x, a
    mov a, vbase
    or a, #V_SRCN
    mov DSP_ADDR, a
    mov a, instruments+x
    mov DSP_DATA, a
    mov a, vbase
    or a, #V_ADSR1
    mov DSP_ADDR, a
    mov a, instruments+1+x
    mov DSP_DATA, a
    mov a, vbase
    or a, #V_ADSR2
    mov DSP_ADDR, a
    mov a, instruments+2+x
    mov DSP_DATA, a

    ; Pitch: table[note + transpose], clamped to 0..127
    mov a, arg0
    clrc
    adc a, instruments+3+x
    bpl .pitch_ok
    cmp a, #$C0                 ; carry set: wrapped below 0
    mov a, #127                 ; (mov leaves carry alone)
    bcc .pitch_ok
    mov a, #0
.pitch_ok:
    asl a
    mov x, a
    mov a, vbase
    or a, #V_PITCHL
    mov DSP_ADDR, a
    mov a, pitch_table+x
    mov DSP_DATA, a
    mov a, vbase
    or a, #V_PITCHH
    mov DSP_ADDR, a
    mov a, pitch_table+1+x
    mov DSP_DATA, a

    mov x, cur_voice
    call set_voice_volume

    mov a, voice_bit+x
    mov DSP_ADDR, #KON
    mov DSP_DATA, a
    mov y, #KON_DELAY
.kon_wait:
    dbnz y, .kon_wait
    ret

; ---------------------------------------------------------------------------
; NOTE_OFF: release every held voice playing arg0
; ---------------------------------------------------------------------------
note_off:
    mov x, #7
.loop:
    mov a, v_on+x
    beq .next
    mov a, v_note+x
    cmp a, arg0
    bne .next
    mov a, #0
    mov v_on+x, a
    mov a, voice_bit+x
    or a, kof_shadow
    mov kof_shadow, a
    mov DSP_ADDR, #KOF
    mov DSP_DATA, a
.next:
    dec x
    bpl .loop
    ret

; ---------------------------------------------------------------------------
; ALL_OFF: release all voices
; ---------------------------------------------------------------------------
all_off:
    mov a, #$FF
    mov kof_shadow, a
    mov DSP_ADDR, #KOF
    mov DSP_DATA, a
    mov a, #0
    mov x, #7
.loop:
    mov v_on+x, a
    dec x
    bpl .loop
    ret

; ---------------------------------------------------------------------------
; alloc_voice -> X
;   1. a held voice already playing arg0 (retrigger)
;   2. otherwise the oldest released voice
;   3. otherwise the oldest held voice (voice stealing)
; Ages are 8-bit differences, so ordering is exact within 256 note-ons.
; ---------------------------------------------------------------------------
alloc_voice:
    mov x, #7
.same_note:
    mov a, v_on+x
    beq .same_next
    mov a, v_note+x
    cmp a, arg0
    beq .done
.same_next:
    dec x
    bpl .same_note

    mov y, #0                   ; pass 0: released voices only; pass 1: any
.pass:
    mov best_v, #$FF
    mov best_age, #0
    mov x, #7
.scan:
    cmp y, #0
    bne .candidate
    mov a, v_on+x
    bne .scan_next
.candidate:
    mov a, age_ctr
    setc
    sbc a, v_age+x
    cmp a, best_age
    bcc .scan_next
    mov best_age, a
    mov best_v, x
.scan_next:
    dec x
    bpl .scan
    mov x, best_v
    bpl .done
    inc y
    bra .pass
.done:
    ret

; ---------------------------------------------------------------------------
; set_voice_volume: X = voice (preserved)
;   amp   = vel * chan_vol / 128
;   left  = amp * min(127, 2 * (127 - pan)) / 128
;   right = amp * min(127, 2 * pan) / 128
; ---------------------------------------------------------------------------
set_voice_volume:
    mov a, x
    xcn a
    mov vbase, a

    mov a, v_vel+x
    mov y, chan_vol
    mul ya
    asl a
    mov a, y
    rol a                       ; A = (Y:A) >> 7
    mov amp, a

    mov a, #127
    setc
    sbc a, chan_pan
    asl a
    bpl .left_ok
    mov a, #127
.left_ok:
    mov y, amp
    mul ya
    asl a
    mov a, y
    rol a
    mov tmp0, a
    mov a, vbase
    or a, #V_VOL_L
    mov DSP_ADDR, a
    mov a, tmp0
    mov DSP_DATA, a

    mov a, chan_pan
    asl a
    bpl .right_ok
    mov a, #127
.right_ok:
    mov y, amp
    mul ya
    asl a
    mov a, y
    rol a
    mov tmp0, a
    mov a, vbase
    or a, #V_VOL_R
    mov DSP_ADDR, a
    mov a, tmp0
    mov DSP_DATA, a
    ret

; ---------------------------------------------------------------------------
; refresh_volumes: re-apply volume/pan to every held voice
; ---------------------------------------------------------------------------
refresh_volumes:
    mov x, #7
.loop:
    mov a, v_on+x
    beq .next
    call set_voice_volume
.next:
    dec x
    bpl .loop
    ret

voice_bit:
    db $01, $02, $04, $08, $10, $20, $40, $80
