#!/usr/bin/env python3
"""Build the MIDI synthesizer's boot image.

  1. Encode the instrument bank (tools/soundbank.py) to BRR files and write
     an spcasm include with the sample directory, pitch and instrument tables.
  2. Assemble src/driver/midi_driver.s plus that bank with spcasm.
  3. Pack the RAM image into a standard .spc (PC at the driver entry, DSP
     registers in their power-on state) and convert it with spc_to_hex.py.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import soundbank  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DRIVER = ROOT / "src" / "driver" / "midi_driver.s"
SPC_TO_HEX = ROOT / "tools" / "spc_to_hex.py"

ENTRY = 0x0500          # `org` of the driver's reset label
DIR_ADDR = 0x0200
PITCH_ADDR = 0x0300
INSTR_ADDR = 0x0400
BRR_ADDR = 0x1000


def write_bank(build: Path, driver: Path) -> Path:
    names = list(soundbank.WAVES)
    lines = [
        "; Generated by tools/build_midi_image.py -- do not edit.",
        f"NUM_INSTR = {len(soundbank.INSTRUMENTS)}",
        "",
        f"org ${DIR_ADDR:04X}",
        "sample_dir:",
    ]
    lines += [f"    dw brr_{n}, brr_{n}" for n in names]
    lines += ["", f"org ${PITCH_ADDR:04X}", "pitch_table:"]
    table = soundbank.pitch_table()
    for i in range(0, 256, 16):
        words = [int.from_bytes(table[j:j + 2], "little") for j in range(i, i + 16, 2)]
        lines.append("    dw " + ", ".join(f"${w:04X}" for w in words))
    lines += ["", f"org ${INSTR_ADDR:04X}", "instruments:  ; srcn, adsr1, adsr2, transpose"]
    for ins in soundbank.INSTRUMENTS:
        lines.append(f"    db {names.index(ins.wave)}, ${ins.adsr1:02X}, ${ins.adsr2:02X}, "
                     f"${ins.transpose & 0xFF:02X}  ; {ins.name}")
    lines += ["", f"org ${BRR_ADDR:04X}"]
    for n in names:
        (build / f"{n}.brr").write_bytes(soundbank.brr_encode(soundbank.WAVES[n], loop=True))
        lines.append(f"brr_{n}: incbin \"{n}.brr\"")
    if len(soundbank.INSTRUMENTS) & (len(soundbank.INSTRUMENTS) - 1):
        raise SystemExit("the driver masks the program number: use a power-of-two instrument count")

    bank = build / "image.s"
    driver_rel = os.path.relpath(driver, build)
    bank.write_text(f"include \"{driver_rel}\"\n\n" + "\n".join(lines) + "\n")
    return bank


def pack_spc(ram: bytes, out: Path) -> None:
    if len(ram) > 0xFFC0:
        raise SystemExit(f"image is {len(ram)} bytes; it must end below $FFC0")
    ram = ram.ljust(0x10000, b"\0")
    if any(ram[0xF0:0x100]):
        raise SystemExit("image overlaps the $F0-$FF I/O registers")

    header = bytearray(0x100)
    header[0:33] = b"SNES-SPC700 Sound File Data v0.30"
    header[0x21:0x23] = b"\x1a\x1a"
    header[0x23] = 27                      # no ID666 tag
    header[0x24] = 30
    header[0x25:0x27] = ENTRY.to_bytes(2, "little")
    header[0x27:0x2A] = b"\0\0\0"          # A, X, Y
    header[0x2A] = 0x00                    # PSW
    header[0x2B] = 0xFF                    # SP

    dsp = bytearray(128)
    dsp[0x6C] = 0xE0                       # FLG power-on: soft reset, mute, echo off

    out.write_bytes(bytes(header) + ram + bytes(dsp) + bytes(0x40) + bytes(0x40))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir", type=Path, help="directory for generated files")
    ap.add_argument("--driver", type=Path, default=DRIVER, help="driver source (default: %(default)s)")
    ap.add_argument("--spcasm", default=os.environ.get("SPCASM", "spcasm"), help="spcasm executable")
    args = ap.parse_args()

    build = args.build_dir.resolve()
    build.mkdir(parents=True, exist_ok=True)
    if shutil.which(args.spcasm) is None:
        raise SystemExit(f"spcasm not found ('{args.spcasm}'); set SPCASM=/path/to/spcasm")

    source = write_bank(build, args.driver.resolve())
    ram_bin = build / "midi_boot.bin"
    subprocess.run([args.spcasm, "-f", "plain", str(source), str(ram_bin)], check=True)

    spc = build / "midi_boot.spc"
    pack_spc(ram_bin.read_bytes(), spc)
    subprocess.run([sys.executable, str(SPC_TO_HEX), str(spc), str(build / "midi_boot.spc.hex")], check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
