`timescale 1ns/1ps

// SNES APU MIDI synthesizer for the Sipeed Tang Primer 25K.
//
//   midi_rx (31250 8N1) -> uart_rx -> midi_parser -> midi_mailbox
//     -> APU I/O ports -> SPC700 MIDI driver -> S-DSP -> i2s_tx -> PCM5102A
//
// BOOT_IMAGE is the A-RAM/register image the APU boots from; by default the
// MIDI driver image built by tools/build_midi_image.py (see README).
module primer25k_nanospc_top #(
    parameter         BOOT_IMAGE = "src/data/midi_boot.spc.hex",
    parameter integer MIDI_BAUD  = 31250
) (
    input  wire clk_50m,
    input  wire midi_rx,
    output wire led_ready,
    // PCM5102A: SCK tied low (internal PLL), FMT low (I2S).
    output wire i2s_bclk,
    output wire i2s_lrclk,
    output wire i2s_sdata
`ifdef VERILATOR
    // These ports exist solely in the C++ simulation model.  They are absent
    // from the synthesis elaboration and therefore do not consume FPGA pins.
    ,output wire        sim_running
    ,output wire        sim_snd_rdy
    ,output wire [15:0] sim_audio_l
    ,output wire [15:0] sim_audio_r
    ,output wire        sim_ev_valid
    ,output wire [7:0]  sim_ev_status
    ,output wire [6:0]  sim_ev_data1
    ,output wire [6:0]  sim_ev_data2
    ,output wire [15:0] sim_mb_sent
    ,output wire        sim_mb_dropped
    ,output wire        sim_mb_timeout
    ,output wire        sim_mb_busy
`endif
);

    localparam integer DCLK_HZ = 24528000;

    // ------------------------------------------------------------------------
    // Clock and power-on reset
    // ------------------------------------------------------------------------
    // Gowin_PLL is generated by the Gowin IP Core Generator.  Its mdclk port
    // clocks the generated PLL initialisation controller; use the stable board
    // clock for both inputs.
    wire dclk;

`ifdef VERILATOR
    // The behavioural simulation has no Gowin PLL primitive.  The simulation
    // harness supplies the desired clock rate; hardware always uses the IP.
    assign dclk = clk_50m;
`else
    Gowin_PLL pll_dsp (
        .clkin  (clk_50m),
        .clkout0(dclk),
        .mdclk  (clk_50m)
    );
`endif

    // There is no external reset in this first board test.  Hold the APU in
    // reset for about 10.5 ms after configuration, allowing the PLL's internal
    // startup sequence to settle before the parser begins writing state.
    reg [18:0] por_count = 19'd0;
    wire resetn = &por_count;

    always @(posedge clk_50m) begin
        if (!resetn)
            por_count <= por_count + 19'd1;
    end

    // ------------------------------------------------------------------------
    // MIDI input
    // ------------------------------------------------------------------------
    wire [7:0] rx_byte;
    wire       rx_valid;
    wire       ev_valid;
    wire [7:0] ev_status;
    wire [6:0] ev_data1;
    wire [6:0] ev_data2;

    uart_rx #(.CLK_HZ(DCLK_HZ), .BAUD(MIDI_BAUD)) midi_uart (
        .clk       (dclk),
        .resetn    (resetn),
        .rx        (midi_rx),
        .data      (rx_byte),
        .valid     (rx_valid),
        .frame_err ()
    );

    midi_parser parser (
        .clk       (dclk),
        .resetn    (resetn),
        .in_valid  (rx_valid),
        .in_byte   (rx_byte),
        .ev_valid  (ev_valid),
        .ev_status (ev_status),
        .ev_data1  (ev_data1),
        .ev_data2  (ev_data2)
    );

    // ------------------------------------------------------------------------
    // Mailbox -> APU
    // ------------------------------------------------------------------------
    wire        apu_running;
    wire [1:0]  port_a;
    wire        port_wr_n;
    wire        port_cs;
    wire [7:0]  port_din;
    wire [7:0]  port_dout;
    wire [15:0] mb_sent;
    wire        mb_dropped;
    wire        mb_timeout;
    wire        mb_busy;

    midi_mailbox mb (
        .clk         (dclk),
        .resetn      (resetn),
        .apu_running (apu_running),
        .ev_valid    (ev_valid),
        .ev_status   (ev_status),
        .ev_data1    (ev_data1),
        .ev_data2    (ev_data2),
        .port_a      (port_a),
        .port_wr_n   (port_wr_n),
        .port_cs     (port_cs),
        .port_din    (port_din),
        .port_dout   (port_dout),
        .sent_count  (mb_sent),
        .dropped     (mb_dropped),
        .ack_timeout (mb_timeout),
        .busy        (mb_busy)
    );

    wire        snd_rdy;
    wire [15:0] audio_l;
    wire [15:0] audio_r;

    apu_core #(
        .MEM_INIT_FILE(BOOT_IMAGE)
    ) apu (
        .clk       (dclk),
        .resetn    (resetn),
        .running   (apu_running),
        .port_a    (port_a),
        .port_wr_n (port_wr_n),
        .port_cs   (port_cs),
        .port_din  (port_din),
        .port_dout (port_dout),
        .snd_rdy   (snd_rdy),
        .audio_l   (audio_l),
        .audio_r   (audio_r)
    );

    // ------------------------------------------------------------------------
    // I2S output
    // ------------------------------------------------------------------------
    // Reset only by power-on so the DAC sees stable clocks (and silence)
    // while the SPC image is still being parsed.
    i2s_tx i2s (
        .clk          (dclk),
        .resetn       (resetn),
        .sample_valid (snd_rdy),
        .sample_l     (audio_l),
        .sample_r     (audio_r),
        .bclk         (i2s_bclk),
        .lrclk        (i2s_lrclk),
        .sdata        (i2s_sdata)
    );

    // ------------------------------------------------------------------------
    // Status LED
    // ------------------------------------------------------------------------
    // Solid once the APU is running; after the first non-zero sample, bit 14
    // of the sample counter blinks it at ~1 Hz. A mailbox error (driver not
    // acknowledging, or command FIFO overflow) turns it off.
    reg [14:0] sample_count = 15'd0;
    reg        audio_seen = 1'b0;

    always @(posedge dclk) begin
        if (!apu_running) begin
            sample_count <= 15'd0;
            audio_seen   <= 1'b0;
        end else if (snd_rdy) begin
            sample_count <= sample_count + 15'd1;
            if ((audio_l != 16'h0000) || (audio_r != 16'h0000))
                audio_seen <= 1'b1;
        end
    end

    assign led_ready = !resetn                  ? 1'b0 :
                       !apu_running             ? 1'b0 :
                       (mb_timeout | mb_dropped) ? 1'b0 :
                       !audio_seen              ? 1'b1 :
                                                  sample_count[14];

`ifdef VERILATOR
    assign sim_running    = apu_running;
    assign sim_snd_rdy    = snd_rdy;
    assign sim_audio_l    = audio_l;
    assign sim_audio_r    = audio_r;
    assign sim_ev_valid   = ev_valid;
    assign sim_ev_status  = ev_status;
    assign sim_ev_data1   = ev_data1;
    assign sim_ev_data2   = ev_data2;
    assign sim_mb_sent    = mb_sent;
    assign sim_mb_dropped = mb_dropped;
    assign sim_mb_timeout = mb_timeout;
    assign sim_mb_busy    = mb_busy;
`endif

endmodule
