`timescale 1ns/1ps

// Standalone SNES APU smoke test for the Sipeed Tang Primer 25K.
//
// This deliberately omits NanoSPC's HDMI, MicroSD, UART, and user-interface
// layers.  It bootstraps the bundled SPC image from inferred A-RAM, runs the
// S-SMP/SPC700 plus S-DSP, and turns the READY LED into a run-status indicator.
module primer25k_nanospc_top (
    input  wire clk_50m,
    output wire led_ready
`ifdef VERILATOR
    // These ports exist solely in the C++ simulation model.  They are absent
    // from the synthesis elaboration and therefore do not consume FPGA pins.
    ,output wire sim_snd_rdy
    ,output wire [15:0] sim_audio_l
    ,output wire [15:0] sim_audio_r
`endif
);

    // ------------------------------------------------------------------------
    // Clock and power-on reset
    // ------------------------------------------------------------------------
    // Gowin_PLL is generated by the Gowin IP Core Generator.  Its mdclk port
    // clocks the generated PLL initialisation controller; use the stable board
    // clock for both inputs.
    wire dclk;

`ifdef VERILATOR
    // The behavioural simulation has no Gowin PLL primitive.  The simulation
    // harness supplies the desired clock rate; hardware always uses the IP.
    assign dclk = clk_50m;
`else
    Gowin_PLL pll_dsp (
        .clkin  (clk_50m),
        .clkout0(dclk),
        .mdclk  (clk_50m)
    );
`endif

    // There is no external reset in this first board test.  Hold the APU in
    // reset for about 10.5 ms after configuration, allowing the PLL's internal
    // startup sequence to settle before the parser begins writing state.
    reg [18:0] por_count = 19'd0;
    wire resetn = &por_count;

    always @(posedge clk_50m) begin
        if (!resetn)
            por_count <= por_count + 19'd1;
    end

    // ------------------------------------------------------------------------
    // S-SMP/SPC700 <-> S-DSP <-> shared 64 KiB A-RAM
    // ------------------------------------------------------------------------
    wire        smp_en;
    wire        smp_we_n;
    wire [15:0] smp_a;
    wire [7:0]  smp_do;
    wire [7:0]  smp_di;

    wire [15:0] ram_a;
    wire [7:0]  ram_din;
    wire [7:0]  ram_dout;
    wire        ram_wr;

    wire [2:0]  dsp_phase;
    wire        dsp_last_phase;
    // Kept public only for the Verilator smoke-capture harness.  The comments
    // are ignored by synthesis and do not add FPGA I/O.
    wire        snd_rdy /* verilator public */;
    wire [15:0] audio_l /* verilator public */;
    wire [15:0] audio_r /* verilator public */;

    // The parser loads CPU, S-SMP, and S-DSP registers from the SPC image
    // while the APU is disabled.  Only after parser_done may the real CPU run.
    wire        parser_done;
    wire        parser_rd;
    wire [16:0] parser_a;
    wire        cpu_dbg_wr;
    wire        smp_dbg_wr;
    wire [7:0]  smpcpu_dbg_reg;
    wire [7:0]  smpcpu_dbg_din;
    wire        dsp_dbg_wr;
    wire [7:0]  dsp_dbg_reg;
    wire [7:0]  dsp_dbg_din;

    reg         parser_start = 1'b0;
    reg         core_enable = 1'b0;
    reg         spc_reset = 1'b1;

    localparam [1:0] BOOT_RESET = 2'd0;
    localparam [1:0] BOOT_PARSE = 2'd1;
    localparam [1:0] BOOT_RUN   = 2'd2;
    reg [1:0] boot_state = BOOT_RESET;

    always @(posedge dclk) begin
        if (!resetn) begin
            boot_state   <= BOOT_RESET;
            parser_start <= 1'b0;
            core_enable  <= 1'b0;
            spc_reset    <= 1'b1;
        end else begin
            // parser_start is a one-clock pulse.
            parser_start <= 1'b0;

            case (boot_state)
                BOOT_RESET: begin
                    core_enable  <= 1'b0;
                    spc_reset    <= 1'b1;
                    parser_start <= 1'b1;
                    boot_state   <= BOOT_PARSE;
                end

                BOOT_PARSE: begin
                    // Release the APU reset.  With core_enable still low,
                    // debug writes from spc_parser initialise its state.
                    spc_reset <= 1'b0;
                    if (parser_done) begin
                        core_enable <= 1'b1;
                        boot_state  <= BOOT_RUN;
                    end
                end

                default: begin
                    spc_reset   <= 1'b0;
                    core_enable <= 1'b1;
                end
            endcase
        end
    end

    wire apu_resetn = resetn & ~spc_reset;

    SMP smp (
        .CLK             (dclk),
        .RST_N           (apu_resetn),
        .ENABLE          (core_enable & smp_en & dsp_last_phase),
        .A               (smp_a),
        .DI              (smp_di),
        .DO              (smp_do),
        .WE_N            (smp_we_n),
        .PA              (2'b00),
        .PARD_N          (1'b1),
        .PAWR_N          (1'b1),
        .CPU_DI          (8'h00),
        .CPU_DO          (),
        .CS              (1'b0),
        .CS_N            (1'b1),
        .DBG_REG         (smpcpu_dbg_reg),
        .DBG_DAT_IN      (smpcpu_dbg_din),
        .DBG_SMP_DAT     (),
        .DBG_CPU_DAT     (),
        .DBG_CPU_DAT_WR  (cpu_dbg_wr),
        .DBG_SMP_DAT_WR  (smp_dbg_wr),
        .BRK_OUT         ()
    );

    DSP dsp (
        .CLK         (dclk),
        .RST_N       (apu_resetn),
        .ENABLE      (core_enable),
        .PHASE       (dsp_phase),
        .LAST_PHASE  (dsp_last_phase),
        .SMP_EN      (smp_en),
        .SMP_A       (smp_a),
        .SMP_DO      (smp_do),
        .SMP_DI      (smp_di),
        .SMP_WE_N    (smp_we_n),
        .RAM_A       (ram_a),
        .RAM_DI      (ram_dout),
        .RAM_DO      (ram_din),
        .RAM_WR      (ram_wr),
        .LRCK        (),
        .BCK         (),
        .SDAT        (),
        .SND_RDY     (snd_rdy),
        .AUDIO_L     (audio_l),
        .AUDIO_R     (audio_r),
        .DBG_REG     (dsp_dbg_reg),
        .DBG_DAT_IN  (dsp_dbg_din),
        .DBG_DAT_OUT (),
        .DBG_DAT_WR  (dsp_dbg_wr)
    );

    test_aram #(
        .MEM_INIT_FILE("src/data/test_spc.spc.hex")
    ) aram (
        .clk    (dclk),
        .din    (ram_din),
        .dout   (ram_dout),
        .wr     (ram_wr),
        .a      (ram_a),
        .spc_rd (parser_rd),
        .spc_wr (1'b0),
        .spc_a  (parser_a),
        .length (),
        .fade   ()
    );

    spc_parser parser (
        .clk             (dclk),
        .resetn          (resetn),
        .start           (parser_start),
        .done            (parser_done),
        .parser_rd       (parser_rd),
        .parser_a        (parser_a),
        .aram_dout       (ram_dout),
        .cpu_dbg_wr      (cpu_dbg_wr),
        .smp_dbg_wr      (smp_dbg_wr),
        .smpcpu_dbg_reg  (smpcpu_dbg_reg),
        .smpcpu_dbg_din  (smpcpu_dbg_din),
        .dsp_dbg_wr      (dsp_dbg_wr),
        .dsp_dbg_reg     (dsp_dbg_reg),
        .dsp_dbg_din     (dsp_dbg_din)
    );

    // ------------------------------------------------------------------------
    // Status LED
    // ------------------------------------------------------------------------
    // Before audible PCM is observed, a solid LED means the snapshot parser
    // completed.  Once non-zero samples arrive, bit 14 gives an approximately
    // 1 Hz visible blink at a 32 kHz sample rate.
    reg [14:0] sample_count = 15'd0;
    reg        audio_seen = 1'b0;

    always @(posedge dclk) begin
        if (!apu_resetn) begin
            sample_count <= 15'd0;
            audio_seen   <= 1'b0;
        end else if (snd_rdy) begin
            sample_count <= sample_count + 15'd1;
            if ((audio_l != 16'h0000) || (audio_r != 16'h0000))
                audio_seen <= 1'b1;
        end
    end

    assign led_ready = !resetn      ? 1'b0 :
                       !core_enable ? 1'b0 :
                       !audio_seen  ? 1'b1 :
                                      sample_count[14];

`ifdef VERILATOR
    assign sim_snd_rdy = snd_rdy;
    assign sim_audio_l = audio_l;
    assign sim_audio_r = audio_r;
`endif

endmodule
